# Generated by Django 5.0.3 on 2024-03-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_staff', 'Can view staff'), ('add_staff', 'Can add staff'))},
        ),
    ]
